### ISSUE TITLE
Implement network-adjusted time

### ISSUE THREAD

**Issue by styppo** [nimiq-network/core#106]

**Comment by sisou** [comment]
I started thinking about this. And I think the best solution would be to have the backbone nodes synced to the real time (via pool.ntp.org for example) and the browser clients synced to the backbone nodes. That way all the browsers would not flood the NTP pool servers.

A `Time` class would then have to be implemented that enables getting the real time, e.g. via `Time.now()` and also has getter methods for `.offset` and `.localTime`, for when they are required.

The real time would then have to be used everywhere in the code base for creating and checking blocks etc.

A few NPM modules that are maybe worth investigating are:
* https://www.npmjs.com/package/timesync: Enables syncing either to one server or multiple peers. Supports syncing via WebSockets and WebRTC.
* https://www.npmjs.com/package/ntp-client: Basic, no-dependency NTP client in javascript.
* https://www.npmjs.com/package/sntp

**Comment by mar-v-in** [comment]
@sisou beside the way backbone nodes connect to the network, there is no difference between them and browser nodes and this is exactly how it should be. Granting backbone nodes some sort of time "authority" is not desired.  Bitcoin solved this using a "Network-adjusted time", the median of the timestamps returned by all nodes connected to you

**Comment by sisou** [comment]
So, from the [Bitcoin Wiki](https://en.bitcoin.it/wiki/Block_timestamp) I got this:

> A timestamp is accepted as valid if it is greater than the median timestamp of previous 11 blocks, and less than the network-adjusted time + 2 hours. "Network-adjusted time" is the median of the timestamps returned by all nodes connected to you. As a result, block timestamps are not exactly accurate, and they do not even need to be in order. Block times are accurate only to within an hour or two.

Originally, I was interested in the time-syncing to make the difficulty adjustments smoother. But it turns out, timestamps that are "off" by up to 2 hours are accepted (for Nimiq this could be 2/10 of an hour, because Nimiq's block time is 10x faster?). So it comes down to the number of blocks being used for the difficutly adjustment and thus the current variation is just because currently that is only 10 blocks.

How strict does the time-keeping then have to be for Nimiq?

**Comment by mar-v-in** [comment]
We currently do the following regarding block times in Nimiq:
1. A block must be newer than its predecessor (to ensure this the miner uses `max(currentTime, lastBlockTime+1)`)
2. A block must not be more than 15 minutes in the future from current local time.

This is why the blockchain works pretty well even without time syncing, although timestamps might be off a bit (approx -1 to +15 minutes) and some clients deny certain blocks because they look like being "from the future" (when in reality the local time is just off more than 15 minutes) which will let them try to create a fork. 

With network-adjusted time we can make sure that wrong local time does no longer cause creation of a fork (that would be denied by the network anyway).

**Comment by sisou** [comment]
Ok, good arguments ;). 

I tried looking at the messenges code but could not find the actual contents of each message. Is a peer's local time currently submitted on initial handshake?

**Comment by styppo** [comment]
Closed via d3c4669.
