### ISSUE TITLE
The transfer UI with an empty wallet is not very useful

### ISSUE THREAD

**Issue by elopio** [nimiq-network/core#147]
## New issue checklist

- [x] I have read all of the [`README`](../README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Browser version(s): Firefox 52.0.1, Ubuntu 17.10
- Reproducible in the testnet?: Yes 

#### Expected behavior

When the wallet is empty, the UI shouldn't offer the option to make transfers.

An account with 0 balance is a great indication that the person is exploring nimiq for the first time. So this is a great opportunity to offer some contextual help for newcomers. Maybe the space could be used to explain that you can get nimiqs by waiting and continue mining, or by asking somebody to make a transfer to your account.

#### Actual behavior

When my balance is 0, I get the same UI I would get when I have some nimiqs. There is a textfield for account number, another for amount, and a disabled button to send transaction. There is no way to get this button enabled, so that part of the UI is useless.

#### Steps to reproduce

Open the betanet.
Transfer all your nimiqs.
Open the wallet.

#### Screenshots

![selection_002](https://user-images.githubusercontent.com/617831/26908860-9eb418c8-4bba-11e7-954a-41853066ffd4.png)

**Comment by andrictham** [comment]
Might I suggest an [empty state](http://www.hongkiat.com/blog/mobile-app-empty-state-designs/)? 

![Empty state example](http://media02.hongkiat.com/mobile-app-empty-state-designs/6-empty-state-mobile-app-designs.jpg)

Good user experience is about offering options where there would otherwise be a dead end. In this scenario, what is the most likely action a user might want to take?

This is a decision that the Nimiq team might want to make, but a call-to-action button that nudges users to first get some NET coins might be helpful. Or, since this a betanet, perhaps a nudge toward contributing to the token sale.

**Comment by styppo** [comment]
Moved to https://github.com/nimiq-network/miner/issues/2.
