### ISSUE TITLE
Transferring money to own wallet gives generic error

### ISSUE THREAD

**Issue by brudaswen** [nimiq-network/core#159]
Sending money to yourself does not work and gives generic error message.

#### Expected behavior

Get a error message that says that sending money to your own account does not make any sense.

#### Actual behavior

You get a generic error message: `Sending the transaction failed. You might have an unconfirmed transaction pending. Please try again in a few seconds.`

Console log states actual error: `Mempool: Rejecting transaction - sender and recipient coincide`

#### Steps to reproduce

Mine some Nimiqs and try to send them to yourself

**Comment by sisou** [comment]
Is this fixed with https://github.com/nimiq-network/core/pull/137?

**Comment by styppo** [comment]
@sisou No, PR #137 added the core logic to reject transactions where sender and recipient coincide (this change introduced the console log output @brudaswen mentioned).

The error message is not actually part of the core code. The issue has been fixed in the corresponding repository (https://github.com/nimiq-network/betanet/commit/03b8c3e602f0836a329db001763c74e8bb9cb600).
