### ISSUE TITLE
Wallet balance displays NIM 0.00, prior to established consensus

### ISSUE THREAD

**Issue by miclaus** [nimiq-network/core#183]
## New issue checklist
- [x] I have read all of the [`README`](../README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): -
- Browser version(s): Chrome 59 (Official Build) (64-bit)
- Devices/Simulators/Machine affected: -
- Reproducible in the testnet? (Yes/No): Yes
- Related issues: -

## Question or Feature Request

When reconnecting to the network, the wallet balance displays `NIM 0.00` whilst connecting to peers and prior to established consensus. 

Wouldn't it be nice to have it display a loading spinner / loading dots or the last saved wallet balance, until consensus has been established ?

<img width="600" alt="screen shot 2017-06-22 at 10 13 31" src="https://user-images.githubusercontent.com/4658706/27424120-3d95e6fe-5734-11e7-8d05-5f0f1d78518f.png">

**Comment by Eligioo** [comment]
To add more to this issue, while the betanet is syncing: if you open your wallet your correct  balance will be displayed.

**Comment by andrictham** [comment]
[BlueprintJS](http://blueprintjs.com/docs/#core/components/progress/skeleton) has a concept of UI “skeletons”.

Here’s how it looks like on LinkedIn:
![image](https://user-images.githubusercontent.com/3891147/27766773-7b67ae0e-5f0e-11e7-9737-ac8717ffadd6.png)

It is commonly used to introduce UI elements before asynchronous data can populate it to suggest a partial or loading state. Since the loading state is already clearly communicated with the text “Connecting to peers”, using a placeholder skeleton UI will reinforce it further.

**Comment by styppo** [comment]
Moved to https://github.com/nimiq-network/miner/issues/1

**Comment by miclaus** [comment]
nimiq-network/miner seems to be private.
