### ISSUE TITLE
Nimiq says it does not support Safari Technology Preview.

### ISSUE THREAD

**Issue by futursolo** [nimiq-network/core#207]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): The one runs on the Nimiq Betanet as of 19th July 2017
- Browser version(s): Safari Technology Preview Release 35 (Safari 11.0, WebKit 12604.1.29)
- Devices/Simulators/Machine affected: macOS Sierra 10.12.5
- Reproducible in the testnet? (Yes/No): Yes
- Related issues: N/A

#### Expected behavior
Window finishes initialization, Button `Connect to Network` should show up.

#### Actual behavior
The page initialization fails with the following message:
```
An error occured.
Your browser is not supported yet. Download latest Chrome(which I don't want to).
```

#### Steps to reproduce
Open the browser, type "https://nimiq.com/betanet/" and press enter.

#### Crash log? Screenshots? Videos? Sample project?
Console Output:
```
TypeError: RTCPeerConnection.generateCertificate is not a function. (In 'RTCPeerConnection.generateCertificate({ name: 'ECDSA', namedCurve: 'P-256' })', 'RTCPeerConnection.generateCertificate' is undefined)
```

Functions and properties of RTCPeerConnection:
```
connectionState: "new"
currentLocalDescription: null
currentRemoteDescription: null
iceConnectionState: "new"
iceGatheringState: "new"
localDescription: null
onconnectionstatechange: null
ondatachannel: null
onicecandidate: null
oniceconnectionstatechange: null
onicegatheringstatechange: null
onnegotiationneeded: null
onsignalingstatechange: null
ontrack: null
pendingLocalDescription: null
pendingRemoteDescription: null
remoteDescription: null
signalingState: "stable"
```
Functions and properties of RTCPeerConnection Prototype:
```
addIceCandidate()
addTrack()
addTransceiver()
close()
connectionState
constructor: function()
createAnswer()
createDataChannel()
createOffer()
currentLocalDescription
currentRemoteDescription
getConfiguration()
getReceivers()
getSenders()
getStats()
getTransceivers()
iceConnectionState
iceGatheringState
localDescription
onconnectionstatechange
ondatachannel
onicecandidate
oniceconnectionstatechange
onicegatheringstatechange
onnegotiationneeded
onsignalingstatechange
ontrack
pendingLocalDescription
pendingRemoteDescription
remoteDescription
removeTrack()
setConfiguration()
setLocalDescription()
setRemoteDescription()
signalingState
```
## Question or Feature Request
Probably should stick to WebSocket as WebRTC is still a working draft.

**Comment by sisou** [comment]
This is likely fixed by #206, which removes the WebRTC polyfill. When master will be merged back into the betanet branch, this will be resolved.

If necessary, #206, or parts of it(?), could be merged into the betanet branch in the meantime.

**Comment by styppo** [comment]
@futursolo 
> Probably should stick to WebSocket as WebRTC is still a working draft.
This would defeat the whole purpose of a browser-based blockchain, wouldn't it? It's not possible to do direct browser-to-browser communication using WebSockets alone, so we would end up with a lame, much more centralised network topology.

@sisou 
> This is likely fixed by #206, which removes the WebRTC polyfill.
Right, #206 should indeed fix it. It's not on the betanet branch yet because the Betanet UI is broken on Microsoft Edge (and since #206 adds core support for Edge, you would actually see the broken UI then).

**Comment by futursolo** [comment]
@styppo I probably misstated my point of view. What I was trying to say is, it's better to wait WebRTC to become more mature(i.e.: become a living standard & gain more browser support) before we actual adopt it. There's nothing wrong on using non-standardized technologies. However, when it comes to something that requires stability, these technologies become potential unstable factors because of compatibility issues, doesn't it?

Also, IMO, particularly, WebRTC still have to solve their privacy issues. Site owners can use WebRTC to get your actual IP Addresses even if you are visiting behind a proxy.

Despite that, Nimiq is an awesome project, keep up the good work!

**Comment by mar-v-in** [comment]
@futursolo I think that WebRTC is ready. We should not argue that we can not use new technology because it not 100% stable. Given that there are no 100% stable standards (i.e. HTTP/1.1, which we all use for many years, was last updated in 2014), it doesn't matter if we wait for any "stable" stamp on it.
- Nimiq is in development too, so it doesn't matter it this point if the technology stack we use is in development, if it is ready at when we are.
- Nimiq requires peer-to-peer networking. There is nothing to discuss about that feature. There are numerous ways to do browser-(supported) peer-to-peer, but only WebRTC and ObjectRTC are likely to exist in a few years (flash is already phasing out, silverlight and java are already gone). WebRTC is widely implemented (only Edge does not support it) and is "already" a working draft and w3c, whereas ORTC is only implemented by Edge and still an early draft. So basically there is exactly one technology we can use and that is WebRTC. By end of year, I expect that we will support >75% of browsers using peer-to-peer technology.
- The actual problem here is that our code is not perfect in detecting supported or unsupported browser implementations. We can still fallback to a non-p2p mode for legacy clients if necessary.
- WebRTC leaking your local IP-address is not an issue of the standard, but of the implementation. The standard allows to client to only use a TURN-ICE candidate, which will only leak the IP address of a proxy server. However, this is not how peer-to-peer works, so browsers tend to not do this.

We will of course update our code to be on par with latest WebRTC standard and still compatible with the majority of web browsers.

**Comment by sisou** [comment]
@futursolo Have you tested the Luna miner (https://nimiq.com/miner) with Safari Technology Preview?

**Comment by futursolo** [comment]
@sisou Yes, I tested Luna when it came out. It works on Safari Technology Preview Release 44 and Safari 11.0.1(macOS High Sierra 10.13.1).
