### ISSUE TITLE
Block mined but not rewarded

### ISSUE THREAD

**Issue by jsappme** [nimiq-network/core#253]
Mining using the node js client, it found a block but never received the award for it. How is it possible?

Here is the proof:

![14149](https://user-images.githubusercontent.com/13439477/33408053-ee7cd350-d539-11e7-8420-f520b8929d62.png)

The balance of this account was still at 0 after it found the block. 

Address: NQ53 3MDS KC57 7MBL H3UV 9Q4Y NY77 LGV2 3E5G

**Comment by jsappme** [comment]
I am experiencing this issue at a rate around 1/10 block mined. It's not negligible.

**Comment by styppo** [comment]
In general, this can happen if you mine a block that is abandoned because another fork grows longer.

In this particular case, I cannot find anything wrong with the block reward. The given address has mined 10 blocks (14149, 14210, 14212, 14253, 14258, 14361, 14387, 14389, 14410, 14439) and has a balance of 50 coins. Looks correct to me.

**Comment by jsappme** [comment]
After mining 14149 the balance was missing $5 for a while. Is it possible that it fixed itself?

**Comment by slug23** [comment]
styppo obviously would have official tools to give you the list, but this would agree
https://nimiq.mopsus.com/addr/NQ533MDSKC577MBLH3UV9Q4YNY77LGV23E5G
