### ISSUE TITLE
Use ASIC-resistant proof of work

### ISSUE THREAD

**Issue by styppo** [nimiq-network/core#38]

**Comment by jamesbrunet** [comment]
Some suggestions for you folks, although you're likely already aware:

Some alternative cryptocurrencies like Monero use the cryptonight algorithm which is memory-hard. There is not as big of a gap between GPU and CPU implementations because of this, and there exists no ASIC implementation yet. It is also possible to implement cryptonight mining in-browser. In fact, some mining pools (minergate come to mind) offer this functionality already. 

Another, more novel, solution would be implementing the cuckoo cycle PoW.

**Comment by rraallvv** [comment]
In [this blog post](https://medium.com/nimiq-network/nimiq-faq-11e77b0030b3) they say it should be already implemented by now, is that already the case? Thanks.

> **Your current proof of work is Sha256. Is this also intended for the Mainnet or are you considering ASIC resistant PoW algorithms?**
> 
> We will switch to an ASIC-resistant proof-of-work as soon as possible. Definitely before the Mainnet launch. We have excluded Argon2 (too slow to verify). With WebAssembly we can use most algorithms with near to native performance, but only the newest browsers have support for it (e.g. Firefox ESR does not have it yet, Safari will have it in the upcoming 11 release). WebCrypto API could be fallback in case WebAssembly support is insufficient at Mainnet Launch. We are confident we will find a proper solution.

**Comment by AndrewBogushevich** [comment]
@jamesbrunet @rraallvv,
AFAIK Nimiq uses argon2d algo since luna testnet(months ago). It is "memory-hard", GPU-resistant and ASIC-resistant. Compared to cryptonight, my mobile phone can calculate 700h/s instead of 10h/s(cryptonight) which is important for verifying blockchain.

**Comment by rraallvv** [comment]
@AndrewBogushevich thanks for the clarification.
